### ISSUE TITLE
/Volumes/OpenFOAM-v2112/etc/bashrc:source:12: no such file or directory: /Volumes/OpenFOAM-v2112/etc/bashrc

### ISSUE THREAD

**Issue by AnvarAtayev** [gerlero/openfoam2112-app#1]
I seem to get `/Volumes/OpenFOAM-v2112/etc/bashrc:source:12: no such file or directory: /Volumes/OpenFOAM-v2112/etc/bashrc` this when I run `openfoam2112`
![Screenshot 2022-02-15 at 14 43 17](https://user-images.githubusercontent.com/70859208/154084914-5e426c4c-00bc-44ff-9191-c2923751c3ba.png)
 
Any help would be appreciated.

Thank you for the great work!

**Comment by gerlero** [comment]
Thanks! The `openfoam2112` link seems to be broken. I'll try to trace the issue and fix it.

For now, does it work if you launch the app itself (or by running ```/Applications/OpenFOAM-v2112.app/Contents/MacOS/openfoam```, which ought to be the same)?

**Comment by AnvarAtayev** [comment]
Thank you for the prompt reply. Yes it does indeed. Thank you for the suggestion. 

![Screenshot 2022-02-15 at 14 54 00](https://user-images.githubusercontent.com/70859208/154087067-84812200-1e60-45ec-9d5e-d9753ee055ef.png)

**Comment by gerlero** [comment]
Fixed in v1.0.2 (```brew upgrade openfoam2112```)

Thank you @AnvarAtayev
