### ISSUE TITLE
Integrating swak4Foam?

### ISSUE THREAD

**Issue by BrushXue** [gerlero/openfoam2112-app#11]
Some issues need to be resolved.
1. Broken python 2.7 integration since Monterey.
2. swak4Foam is built into `FOAM_USER_APPBIN` and `FOAM_USER_LIBBIN`. How will your package handle this?

**Comment by gerlero** [comment]
> 1. Broken python 2.7 integration since Monterey.

Python 2.7 has been EOL'd for over 2 years. It's no longer available from Homebrew and will be removed completely from macOS in 12.3. I don't think it's worth it to support that use case.

> 2. swak4Foam is built into `FOAM_USER_APPBIN` and `FOAM_USER_LIBBIN`. How will your package handle this?

I'm not a swak4Foam user. Does it compile and run without a case-sensitive filesystem?

**Comment by BrushXue** [comment]
OK it makes more sense to remove all python2 related components in swak4Foam. I haven't tested it in a case-sensitive environment yet but I can try to create a fork that works on macOS directly(built into `FOAM_APPBIN` and `FOAM_LIBBIN`), then you can integrate it with no harm.

**Comment by gerlero** [comment]
Did you already try to compile it directly (i.e., not inside of a case-sensitive volume)?

**Comment by BrushXue** [comment]
> Did you already try to compile it directly (i.e., not inside of a case-sensitive volume)?

Not yet. I created a case-sensitive APFS volume and compile everything inside.

**Comment by gerlero** [comment]
Any update on this? Were you able to try it?

**Comment by BrushXue** [comment]
I'm upgrading macOS 12.3 which removes python 2.7. The patch needs to be updated. Will get back to you later.

**Comment by BrushXue** [comment]
I've tested the new patch https://github.com/BrushXue/OpenFOAM-AppleM1/blob/main/swak4Foam.patch
Since your OpenFOAM installation is read-only, the only way to integrate swak4Foam is to modify `files` and `options` so that all files are compiled to `FOAM_APPBIN` and `FOAM_LIBBIN`.
If that's too complicated for your work, maybe people can just compile it in their own folders.

**Comment by gerlero** [comment]
> If that's too complicated for your work, maybe people can just compile it in their own folders.

I'd rather recommend this workflow (AFAIK that's how it's done on Linux too).
