### ISSUE TITLE
Multiple versions ?

### ISSUE THREAD

**Issue by ShangWangNUST** [gerlero/openfoam2112-app#14]
Thank you for your excellent work！ Is it possible to provide multiple versions, such as OpenFOAM 8？

**Comment by gerlero** [comment]
Unfortunately, www.openfoam.org releases thus far do not support macOS natively. E.g. if you try to compile OpenFOAM 9:

```bash
     Your "Darwin" operating system is not supported by this release
    of OpenFOAM. For further assistance, please contact https://openfoam.org
```

**Comment by ShangWangNUST** [comment]
Understand. Thank you for your work.

**Comment by gerlero** [comment]
You're likely already aware of this, but if you need to run those on macOS, I may suggest you try Docker (which actually runs the Linux version via virtualization). E.g. https://openfoam.org/download/8-macos/
