### ISSUE TITLE
Adding paraview as a Homebrew dependency

### ISSUE THREAD

**Issue by BrushXue** [gerlero/openfoam2112-app#21]
Hello,

I just found out that the paraview from [Homebrew](https://formulae.brew.sh/cask/paraview) is more convenient. The `paraview` command is added to the PATH.
```
~ brew install --cask paraview
==> Downloading https://www.paraview.org/paraview-downloads/download.php?submit=
==> Installing Cask paraview
==> Moving App 'ParaView-5.10.1.app' to '/Applications/ParaView-5.10.1.app'
==> Linking Binary 'paraview' to '/opt/homebrew/bin/paraview'
🍺  paraview was successfully installed!
```
Also `paraFoam` will be available.

**Comment by gerlero** [comment]
I tried using `paraFoam` before with Homebrew-installed ParaView and IIRC it did not work. Can you confirm that calling `paraFoam` actually works as expected?

Anyway, I wouldn't want to add `paraview` as a _required_ dependency, but I guess a note on the README and/or the Cask "caveats" telling users how to install it might be helpful.

**Comment by BrushXue** [comment]
I just realized the binary is added by you
But anyway, it works on both your build on bash 
```
$ which paraview
/opt/homebrew/bin/paraview
$ paraFoam
Invalid $PV_PLUGIN_PATH and -plugin-path= not defined
No supplementary ParaView/OpenFOAM reader modules
Using builtin reader: paraFoam -vtk

Created temporary 'OpenFOAM-v2112.foam'

```
and my own build on zsh
```
➜  OpenFOAM-v2112 git:(arm64) ✗ which paraview
/opt/homebrew/bin/paraview
➜  OpenFOAM-v2112 git:(arm64) ✗ paraFoam
Invalid $PV_PLUGIN_PATH and -plugin-path= not defined
No supplementary ParaView/OpenFOAM reader modules
Using builtin reader: paraFoam -vtk

Created temporary 'OpenFOAM-v2112.foam'
```

**Comment by gerlero** [comment]
Thanks!

I can also confirm now that `paraFoam` works with Homebrew ParaView (using the builtin/vtk reader), regardless of whether ParaView was available at the time OpenFOAM was compiled. This tells me that adding `paraview` as a build dependency should not be necessary*.

*Unless one also wishes to compile the OpenFOAM reader module, but I haven't tried that and don't even know if that is viable on macOS.

If you're okay with it, I can add a note to the Installation section telling users they can (should?) install ParaView using Homebrew.

**Comment by BrushXue** [comment]
Yes I agree with you that OpenFOAM doesn't require Paraview to simulate. However, another fact is everyone will use Paraview to visualize it. So please at least add a note telling people there's an easy way to call `paraFoam`.
Also I'm interested in building the OpenFOAM reader module. I know it can display the patch name on the geometry so sometimes it's kind of useful.

**Comment by gerlero** [comment]
> Also I'm interested in building the OpenFOAM reader module. I know it can display the patch name on the geometry so sometimes it's kind of useful.

Unfortunately I don't have time to really work on that (plus the builtin reader is fine for my needs), but if you do find a way to build the module, I'd be really interested in integrating it into this project.

**Comment by BrushXue** [comment]
I give up, as the macOS binary doesn't even have `include` folder. To build the reader module I have to build paraview from source code first. This is already too complicated on Linux, I can't imagine it on a Mac.
