### ISSUE TITLE
Issues on ThirdParty

### ISSUE THREAD

**Issue by Deltaom** [gerlero/openfoam2112-app#37]
Hello, Gerlero

Thanks a lot for your contribution to installation of OpenFOAM on MacOS. It helps a lot. I've just installed it successfully by compiling the source code directly. 

However, when I tried to complied the ThirdParty source codes the same way as I did, some problems occurred when it comes to scotch and related apps. Though I tried to use homebrew to install scotch, just to skip the problem, it seems that by using homebrew, the lib complied is in the form of *.dylib instead of *.so causing the Openfoam not able to load libscotch, which subsequently results in the failure of the application of  decomposePar using scotch method to decompose the meshes.

Do you have any idea about that?

Thanks in advance!

**Comment by gerlero** [comment]
This issue does not directly pertain to this project, as I understand you're not downloading or building from this repo. Is there a reason why you are not able to use the app as provided in this repo?

Nevertheless, the way this project avoids the issue you describe is by forgoing the ThirdParty sources entirely and instead obtaining the relevant dependencies with a package manager (same as with the prepackaged Linux builds), which in this case is Homebrew (see the [Brewfile](Brewfile) and the companion [`gerlero/openfoam` tap](https://github.com/gerlero/homebrew-openfoam), which has variants of some formulae that will work with OpenFOAM). Then, OpenFOAM is explicitly configured to use these dependencies (see the [configure.sh](configure.sh) file).
