### ISSUE TITLE
Some tutorial run scripts fail with library errors

### ISSUE THREAD

**Issue by gerlero** [gerlero/openfoam2112-app#5]
e.g. `$FOAM_TUTORIALS/basic/laplacianFoam/flange/Allrun-parallel`.

See https://develop.openfoam.com/Development/openfoam/-/issues/1661 and
https://develop.openfoam.com/Development/openfoam/-/issues/1664.

**Comment by AnvarAtayev** [comment]
Not sure if this is the same error, but execution fails when I run certain tutorial scripts. It seems to be that OpenFOAM can't find `___.so` files.

For example, when I run `$FOAM_TUTORIALS/incompressible/simpleFoam/backwardFacingStep2D`, I get the following warning in the `simpleFoam.log` file.
![Screenshot 2022-02-16 at 11 33 54](https://user-images.githubusercontent.com/70859208/154256849-1a6bf6e0-e7c4-4173-ace7-1eea96dbc159.png)

**Comment by AnvarAtayev** [comment]
Initially found since I tried to run it where I was calling for `libforces.so`,
![Screenshot 2022-02-16 at 11 37 37](https://user-images.githubusercontent.com/70859208/154257358-28d00929-4681-49cc-aee3-d1e733d8b771.png)

**Comment by gerlero** [comment]
Seems related. Unfortunately, this specific case doesn't look like it would be covered by #6 as of now (which is failing CI on Intel anyway...). Just out of curiosity, are you using Intel or M1?

A workaround I can find is to re-source the OpenFOAM `etc/bashrc` and then manually input the lines of the `Allrun` script one by one, i.e.:

```sh
source /Volumes/OpenFOAM-v2112/etc/bashrc

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
restore0Dir
runApplication blockMesh
runApplication simpleFoam
```

I get no warnings in `log.simpleFoam` when I run it that way.

**Comment by AnvarAtayev** [comment]
I am running a Mac Mini M1. 

running 
```bash
source /Volumes/OpenFOAM-v2112/etc/bashrc

. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
restore0Dir
runApplication blockMesh
runApplication simpleFoam
```
in the `~/Desktop/backwardFacingStep2D` gives me the same error as before. It is possible that I am doing something wrong here. I have attached my `log.simpleFoam` file in case it is of interest.
![Screenshot 2022-02-16 at 12 41 24](https://user-images.githubusercontent.com/70859208/154266581-a3cc307a-7d05-4229-89fb-bd3b47197d2e.png)


[log.simpleFoam.zip](https://github.com/gerlero/openfoam2112-app/files/8079912/log.simpleFoam.zip)

**Comment by gerlero** [comment]
That's strange. Here's my log after running the same commands on a copy of `$FOAM_TUTORIALS/incompressible/simpleFoam/backwardFacingStep2D` for reference: [log.simpleFoam.zip](https://github.com/gerlero/openfoam2112-app/files/8079978/log.simpleFoam.zip)

Are you running the previous snippet directly from the shell (not as a script)? Only thing I think might help is to add an extra command (this is taken from #6, but in my case I didn't really need it):

```sh
source /Volumes/OpenFOAM-v2112/etc/bashrc
FOAM_DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions
restore0Dir
runApplication blockMesh
runApplication simpleFoam
```

**Comment by AnvarAtayev** [comment]
I'm running the snippets directly from the shell in the copied `$FOAM_TUTORIALS/incompressible/simpleFoam/backwardFacingStep2D` directory (which is for testing purposes in my `~/Desktop/...`.

Using the new snippet you provided, OpenFOAM seems to run and no warnings are raised in the log.simpleFoam file. Interesting... Are you also running an M1?

**Comment by gerlero** [comment]
Yup, I'm running an M1 MacBook Air.

I'm still working on #6; trying a different approach to fix this.

**Comment by gerlero** [comment]
v1.1.0 is out with #6 and should fix all of these. Thanks @AnvarAtayev
